apiVersion: v1
kind: Pod
metadata:
  labels:
    build-name: label-build-name
spec:
  containers:
  - name: maven
    image: maven:3-jdk-8-alpine
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /root/.m2
      name: m2
    - mountPath: /var/run/docker.sock
      name: docker

  - name: git-push
    image: docker.gedoplan.de/git-push
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true

  volumes:
  - name: m2
    persistentVolumeClaim:
      claimName: maven-m2
  - name: docker
    hostPath:
      path: /var/run/docker.sock
