apiVersion: v1
kind: Pod
metadata:
  labels:
    build-name: label-build-name
spec:
  containers:
  - name: maven
    image: maven:3-jdk-8-alpine
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /root/.m2
      name: m2
    - mountPath: /var/run/docker.sock
      name: docker

#  - name: kubectl
#    image: lachlanevenson/k8s-kubectl:v1.13.2
#    command:
#    - cat
#    tty: true

  volumes:
  - name: m2
    persistentVolumeClaim:
      claimName: maven-m2
  - name: docker
    hostPath:
      path: /var/run/docker.sock
