#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: rest-mee
#spec:
#  replicas: 3
#  selector:
#    app: rest-mee
#  template:
#    metadata:
#      labels:
#        app: rest-mee
#    spec:
#      containers:
#      - name: rest-mee
#        image: docker.gedoplan.de/showcase/k8s-demo-rest-mee
#        # Use IfNotPresent for local demo only; omit imagePullPolicy otherwise
#        imagePullPolicy: IfNotPresent
#        ports:
#        - containerPort: 8080
#          protocol: TCP
