pipeline {
	options {
        disableConcurrentBuilds()
    }
	
	agent {
		kubernetes {
			label 'label-agent'
			defaultContainer 'jnlp'
      		yamlFile 'src/main/jenkins/build-pod.yaml'
		}
	}

	stages {
		stage('Checkout project') {
			steps {
				checkout scm: scm, poll: false
			}
		}
		    	
		stage('Build Maven project') {
			steps {
	        	container('maven') {
	            	sh 'mvn -B package'
	        	}
	    	}
		}
		
		stage('Test project') {
			steps {
	    	    container('maven') {
	        	    sh 'echo No tests found'
	        	}
	    	}
		}

		stage('Build Docker image') {
			steps {
	        	container('maven') {
	            	sh 'mvn -Pdocker docker:build'
	        	}
	    	} 
		}

    	stage('Deploy application in test') {
			steps {
	        	container('git-push') {
	        	    sh 'echo Push application into GitOps repository'
	        	}
	    	}
		}
	}
}
