# Default values for rest-war.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: gedoplan/k8s-demo-rest-war
  tag: latest
  # Use IfNotPresent for local demo only; omit pullPolicy otherwise
  pullPolicy: IfNotPresent

port: 8080

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - rest-war.localtest.me

  tls: []

podAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
